### PR TITLE
Create THREERenderer and decouple Renderer from THREEScene

### PR DESCRIPTION
**Pull request by gilbox**
The basic idea is to go from this:

```jsx
<Scene>{/*...*/}</Scene>
```
to this:
```jsx
<Renderer>
 <Scene>{/*...*/}</Scene>
 <Scene>{/*...*/}</Scene>
</Renderer>
```

It could probably use improvement, but looking for feedback on this. This came about because I want to [render a second scene as a background](http://stackoverflow.com/questions/19865537/three-js-set-background-image).

Do you like this general approach? 

I refactored the *cupcake* example to use this approach. The rest of the examples would also need to be refactored. 

note: #59 should be merged first

Here's the cupcake demo. Note that each cupcake is inside of it's own Scene:

2cupcakes

### CODE REVIEW

**Comment by Izzimach** [comment]
Yeah, that makes sense. Might also be useful to generate the Scene standalone and use it later in a renderer. Not sure if that's possible, though.

Let me pull this into the `dev` branch and make changes/tests there, then it can merge into `master` once examples and docs are updated.

**Comment by gilbox** [comment]
> Might also be useful to generate the Scene standalone and use it later in a renderer.

Cool idea, either by allowing a composite component to wrap Scene and define `shouldComponentUpdate` or by exposing a `shouldUpdate` prop on the Scene component.

**Comment by Izzimach** [comment]
Looks like mixing THREEContainer is messing up the internal tree structure and causing some wierd erros. I don't think you're supposed to have multiple children of a custom component created via `createClass`.

I'll see if I can get this to work in the general case. If not, there may be another way such as passing in multiple scenes via props or something.

**Comment by gilbox** [comment]
just noticed this breaks pointerEvents because Scene doesn't have access to the raycaster instance.

**Comment by gilbox** [comment]
> I don't think you're supposed to have multiple children of a custom component created via createClass.

What do you mean by this? Afaik in normal react world you certainly can.

**Comment by Izzimach** [comment]
Oops yeah the children passed in as `props.children` can be >1. I meant the
actual rendered component tree. Notably`render` only lets you return one
node, which is basically the 'child' of a custom component.

But I dunno if that's the real issue or not.

As you said the pointer events are messed up. Probably event listeners
should be attached in `THREERenderer` since that also contains the relevant
canvas element. Then clicks can be forwarded to the scene(s) perhaps.

**Comment by Izzimach** [comment]
Looked at the pointer event stuff this morning. Might need to turn THREEScene into a standard React component instead of one created via `createClass` to properly bind mouse events. More details as events warrant.

**Comment by Izzimach** [comment]
Put this code into a [separate branch](https://github.com/Izzimach/react-three/tree/gilbox-renderer), still needs a lot of work/fixes but it's getting there.

**Pull request closed without merging**
